In [70]:
import math as mt
import numpy as np
import string

In [29]:
#Q1

# constant variables

C = 50
H = 30

# path of the csv file

path = 'Data/iNdata.txt'     

# reading the csv file and calculting the value

with open(path,'r') as f:
    my_file = f.read()
    for num in my_file.split(','):
        val = mt.sqrt((2*C*int(num))/H)
        print(round(val,2) , end = ",")
        

18.26,22.36,24.49,

In [61]:
#Q2

# user inputs for rows and columns
x = 3
y = 5

# dummy matrix of same dimension as specified by user
dum_mat = np.zeros([x,y]) 

#array creation

for i in range(3):
    for j in range(5):
        dum_mat[i][j]= i * j

    
print(dum_mat)




[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [66]:
#Q3

csv_str = "hello,world,apple,boy,xerox"

unsrt_lst = csv_str.split(',')
srtd_lst = sorted(unsrt_lst)
for wd in srtd_lst:
    print(wd, end = ",")
   



apple,boy,hello,world,xerox,

In [69]:
#Q4
whtspc_str = "hello world apple boy xerox"

unst_lst = whtspc_str.split(' ')
srtd_ls = sorted(unst_lst)
for wd in srtd_lst:
    print(wd, end = " ")
   




apple boy hello world xerox 

In [82]:
#Q5

dum_sen = "the world is beautiful For a Reason And that reseon is iftaqil789"

def countAlpDig(x):
    
    '''input: any string
    output: counts letters and digits in the string'''
    
    alpha = string.ascii_lowercase + string.ascii_uppercase
    digits = '0123456789'
    word = 0
    num = 0
    for char in x:
        if char in alpha:
            word += 1
        if char in digits:
            num += 1
    return print('''LETTERS {}
DIGITS {}'''.format(word,num) )
        
countAlpDig(dum_sen)



LETTERS 51
DIGITS 3


In [89]:
#Q6
#csv passowrd file

csv_pswds = "1Rgh$f,$6phjik9,#123Rouyal,12Ryklo#,12Ghsdjdeyeik"

#crtetria of a valiod password

alphaLow = string.ascii_lowercase
alphaUp = string.ascii_uppercase
dig = '0123456789'
spcl_char = '$#@'
min_len = 6
max_len = 12

#password validation code

for pswd in csv_pswds.split(','):
    lw_alp = []
    up_alp = []
    dg = []
    sp_c = []
    
    for char in pswd:
        if char in alphaLow:
            lw_alp.append(char)
        if char in alphaUp:
            up_alp.append(char)
        if char in dig:
            dg.append(char)
        if char in spcl_char:
            sp_c.append(char)
    if len(lw_alp) > 0 and len(up_alp) > 0 and len(dg)>0 and len(sp_c) > 0 and len(pswd) > min_len and len(pswd)< max_len:
        print(pswd, end = ",")
        lw_alp = []
        up_alp = []
        dg = []
        sp_c = []
    


#123Rouyal,12Ryklo#,