In [11]:
import numpy as np

In [27]:
a = np.array([[1,2,4],[4,5,7],[8,9,10]])
b = np.array([[1],[2],[3]])
c = np.array([[3,4,6],[9,8,7],[0,5,6]])
print(a)
print(b)
print(c)

[[ 1  2  4]
 [ 4  5  7]
 [ 8  9 10]]
[[1]
 [2]
 [3]]
[[3 4 6]
 [9 8 7]
 [0 5 6]]


In [39]:
#Q1

def add_mat(x,y):
    
    '''input : array (matrix)
     output : sum or the two input array by matrix addition'''
    
    if x.shape == y.shape:
        return (x + y)
    else:
        return print("Two different size matrix cannot be add")
print(add_mat(a,c))

[[ 4  6 10]
 [13 13 14]
 [ 8 14 16]]


In [78]:
#Q2

def mul_mat(x,y):
    
    '''input: array as matrix
        output: matrix after matrix multiplication two input arrays'''
    
    if x.shape[1] == y.shape[0]:
        mult_val = x @ y
        return mult_val
    else:
        return print("Number of columns of 1st matrix must be same as number of rows in 2nd matrix")
mul_mat(a,b)

                

array([[17],
       [35],
       [56]])

In [79]:
#Q3
def mat_trans(x):
    '''input: an array 
    output: transpose of array'''
    return x.T
mat_trans(a)

array([[ 1,  4,  8],
       [ 2,  5,  9],
       [ 4,  7, 10]])

In [86]:
#Q4
l = ['apple','owl','mango','ant','ball','kite','abeca']
char = "agsdjkeghdj"

def sort_list(x):
    '''input: list, string,numbers
    output: sorted lis,string in alphanetical order'''
    return sorted(x)
sort_list(l)

['abeca', 'ant', 'apple', 'ball', 'kite', 'mango', 'owl']

In [4]:
#Q5
import string 

s = "hsgte:sks,lsdjy;"
def rmv_punc(x):
    
    '''input : string
    output : string free from punctuation'''
    
    punc = string.punctuation
    punc_free = ""
    for char in x:
        if char not in punc:
            punc_free += char
    
    return punc_free
            
rmv_punc(s)



'hsgteskslsdjy'